version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
        - "27017:27017"
    volumes:
        - ./data:/data/db
    networks:
      - demo_network
networks:
    demo_network: