version: '3'

services:
  app:
    build: ./app/
    container_name: go-alpha
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
        - "27017:27017"
    volumes:
        - ./data:/data/db
    networks:
      - backend
networks:
  backend:
    driver: "bridge"